#############################################################################
# Makefile for building: ../bin/DIIS.app/Contents/MacOS/DIIS
# Generated by qmake (2.01a) (Qt 4.7.4) on: Fri May 11 10:39:21 2012
# Project:  DIIS.pro
# Template: app
# Command: /Users/japetrus/PhD/Programs/QtSDK/Desktop/Qt/474/gcc/bin/qmake -o Makefile DIIS.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -m32 -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
CXXFLAGS      = -m32 -O3 -DHAVE_STD -DHAVE_NAMESPACES -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
INCPATH       = -I../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/default -I. -I../../../Programs/QtSDK/Desktop/Qt/474/gcc/lib/QtCore.framework/Versions/4/Headers -I../../../Programs/QtSDK/Desktop/Qt/474/gcc/include/QtCore -I../../../Programs/QtSDK/Desktop/Qt/474/gcc/lib/QtNetwork.framework/Versions/4/Headers -I../../../Programs/QtSDK/Desktop/Qt/474/gcc/include/QtNetwork -I../../../Programs/QtSDK/Desktop/Qt/474/gcc/lib/QtGui.framework/Versions/4/Headers -I../../../Programs/QtSDK/Desktop/Qt/474/gcc/include/QtGui -I../../../Programs/QtSDK/Desktop/Qt/474/gcc/include -I-I../qwt-5.2.2/src -I. -I. -F/Users/japetrus/PhD/Programs/QtSDK/Desktop/Qt/474/gcc/lib
LINK          = g++
LFLAGS        = -m32 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5
LIBS          = $(SUBLIBS) -F/Users/japetrus/PhD/Programs/QtSDK/Desktop/Qt/474/gcc/lib -L/Users/japetrus/PhD/Programs/QtSDK/Desktop/Qt/474/gcc/lib -L/Users/japetrus/PhD/Programs/DIIS/src/qwt-5.2.2/lib -lqwt -framework QtGui -framework QtNetwork -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /Users/japetrus/PhD/Programs/QtSDK/Desktop/Qt/474/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		ConfigFile/ConfigFile.cpp \
		TwoThetaPlot.cpp \
		AppWindow.cpp \
		FilmWidget.cpp \
		AppConfig.cpp \
		TwoThetaWindow.cpp moc_TwoThetaPlot.cpp \
		moc_FilmWidget.cpp \
		moc_AppWindow.cpp \
		moc_AppConfig.cpp \
		moc_LogWidget.cpp \
		moc_TwoThetaWindow.cpp \
		qrc_AppResources.cpp
OBJECTS       = main.o \
		ConfigFile.o \
		TwoThetaPlot.o \
		AppWindow.o \
		FilmWidget.o \
		AppConfig.o \
		TwoThetaWindow.o \
		moc_TwoThetaPlot.o \
		moc_FilmWidget.o \
		moc_AppWindow.o \
		moc_AppConfig.o \
		moc_LogWidget.o \
		moc_TwoThetaWindow.o \
		qrc_AppResources.o
DIST          = ../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/unix.conf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac.conf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac-g++.conf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/qconfig.pri \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_pre.prf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/dwarf2.prf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/debug.prf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_post.prf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/x86_64.prf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/objective_c.prf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt.prf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/moc.prf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/rez.prf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/sdk.prf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/resources.prf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/uic.prf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/lex.prf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/include_source_dir.prf \
		DIIS.pro
QMAKE_TARGET  = DIIS
DESTDIR       = ../bin/
TARGET        = ../bin/DIIS.app/Contents/MacOS/DIIS

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -m32 \
		-g \
		-gdwarf-2 \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile ../bin/DIIS.app/Contents/PkgInfo ../bin/DIIS.app/Contents/Resources/empty.lproj ../bin/DIIS.app/Contents/Info.plist ../bin/DIIS.app/Contents/Resources/icon.icns $(TARGET)

$(TARGET): ui_PreferencesDialog.h ui_GeometryDialog.h ui_MineralSearchDialog.h ui_ImageDialog.h ui_MacroDialog.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) ../bin/DIIS.app/Contents/MacOS/ || $(MKDIR) ../bin/DIIS.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: DIIS.pro  ../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/default/qmake.conf ../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/unix.conf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac.conf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac-g++.conf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/qconfig.pri \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_pre.prf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/dwarf2.prf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/debug.prf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_post.prf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/x86_64.prf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/objective_c.prf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt.prf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/moc.prf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/rez.prf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/sdk.prf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/resources.prf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/uic.prf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/lex.prf \
		../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile DIIS.pro
../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/unix.conf:
../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac.conf:
../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac-g++.conf:
../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/qconfig.pri:
../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/modules/qt_webkit_version.pri:
../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf:
../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf:
../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf:
../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf:
../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_pre.prf:
../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/dwarf2.prf:
../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/debug.prf:
../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf:
../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_post.prf:
../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/x86_64.prf:
../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/objective_c.prf:
../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf:
../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt.prf:
../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf:
../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/moc.prf:
../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/rez.prf:
../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/sdk.prf:
../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/resources.prf:
../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/uic.prf:
../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf:
../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/lex.prf:
../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -o Makefile DIIS.pro

../bin/DIIS.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) ../bin/DIIS.app/Contents || $(MKDIR) ../bin/DIIS.app/Contents 
	@$(DEL_FILE) ../bin/DIIS.app/Contents/PkgInfo
	@echo "APPL????" >../bin/DIIS.app/Contents/PkgInfo
../bin/DIIS.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) ../bin/DIIS.app/Contents/Resources || $(MKDIR) ../bin/DIIS.app/Contents/Resources 
	@touch ../bin/DIIS.app/Contents/Resources/empty.lproj
	
../bin/DIIS.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) ../bin/DIIS.app/Contents || $(MKDIR) ../bin/DIIS.app/Contents 
	@$(DEL_FILE) ../bin/DIIS.app/Contents/Info.plist
	@sed -e "s,@ICON@,icon.icns,g" -e "s,@EXECUTABLE@,DIIS,g" -e "s,@TYPEINFO@,????,g" ../../../Programs/QtSDK/Desktop/Qt/474/gcc/mkspecs/default/Info.plist.app >../bin/DIIS.app/Contents/Info.plist
../bin/DIIS.app/Contents/Resources/icon.icns: resources/icon.icns
	@$(CHK_DIR_EXISTS) ../bin/DIIS.app/Contents/Resources/ || $(MKDIR) ../bin/DIIS.app/Contents/Resources/ 
	@$(DEL_FILE) ../bin/DIIS.app/Contents/Resources/icon.icns
	@$(COPY_FILE) resources/icon.icns ../bin/DIIS.app/Contents/Resources/icon.icns
dist: 
	@$(CHK_DIR_EXISTS) .tmp/DIIS1.0.0 || $(MKDIR) .tmp/DIIS1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/DIIS1.0.0/ && $(COPY_FILE) --parents ConfigFile/ConfigFile.h TwoThetaPlot.h FilmWidget.h AppWindow.h AppConfig.h LogWidget.h TwoThetaWindow.h .tmp/DIIS1.0.0/ && $(COPY_FILE) --parents AppResources.qrc .tmp/DIIS1.0.0/ && $(COPY_FILE) --parents main.cpp ConfigFile/ConfigFile.cpp TwoThetaPlot.cpp AppWindow.cpp FilmWidget.cpp AppConfig.cpp TwoThetaWindow.cpp .tmp/DIIS1.0.0/ && $(COPY_FILE) --parents PreferencesDialog.ui GeometryDialog.ui MineralSearchDialog.ui ImageDialog.ui MacroDialog.ui .tmp/DIIS1.0.0/ && (cd `dirname .tmp/DIIS1.0.0` && $(TAR) DIIS1.0.0.tar DIIS1.0.0 && $(COMPRESS) DIIS1.0.0.tar) && $(MOVE) `dirname .tmp/DIIS1.0.0`/DIIS1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/DIIS1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r ../bin/DIIS.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_TwoThetaPlot.cpp moc_FilmWidget.cpp moc_AppWindow.cpp moc_AppConfig.cpp moc_LogWidget.cpp moc_TwoThetaWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_TwoThetaPlot.cpp moc_FilmWidget.cpp moc_AppWindow.cpp moc_AppConfig.cpp moc_LogWidget.cpp moc_TwoThetaWindow.cpp
moc_TwoThetaPlot.cpp: /usr/local/qwt-5.2.2/include/qwt.h \
		/usr/local/qwt-5.2.2/include/qwt_global.h \
		/usr/local/qwt-5.2.2/include/qwt_plot.h \
		/usr/local/qwt-5.2.2/include/qwt_array.h \
		/usr/local/qwt-5.2.2/include/qwt_text.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_dict.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_item.h \
		/usr/local/qwt-5.2.2/include/qwt_legend_itemmanager.h \
		/usr/local/qwt-5.2.2/include/qwt_double_rect.h \
		/usr/local/qwt-5.2.2/include/qwt_scale_map.h \
		/usr/local/qwt-5.2.2/include/qwt_math.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_printfilter.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_zoomer.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_picker.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_canvas.h \
		/usr/local/qwt-5.2.2/include/qwt_picker.h \
		/usr/local/qwt-5.2.2/include/qwt_polygon.h \
		/usr/local/qwt-5.2.2/include/qwt_event_pattern.h \
		/usr/local/qwt-5.2.2/include/qwt_painter.h \
		/usr/local/qwt-5.2.2/include/qwt_layout_metrics.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_marker.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_curve.h \
		/usr/local/qwt-5.2.2/include/qwt_data.h \
		/usr/local/qwt-5.2.2/include/qwt_scale_widget.h \
		/usr/local/qwt-5.2.2/include/qwt_scale_draw.h \
		/usr/local/qwt-5.2.2/include/qwt_abstract_scale_draw.h \
		/usr/local/qwt-5.2.2/include/qwt_scale_div.h \
		/usr/local/qwt-5.2.2/include/qwt_valuelist.h \
		/usr/local/qwt-5.2.2/include/qwt_double_interval.h \
		/usr/local/qwt-5.2.2/include/qwt_legend.h \
		/usr/local/qwt-5.2.2/include/qwt_symbol.h \
		AppConfig.h \
		ConfigFile/ConfigFile.h \
		ui_PreferencesDialog.h \
		TwoThetaPlot.h
	/Users/japetrus/PhD/Programs/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ TwoThetaPlot.h -o moc_TwoThetaPlot.cpp

moc_FilmWidget.cpp: /usr/local/qwt-5.2.2/include/qwt.h \
		/usr/local/qwt-5.2.2/include/qwt_global.h \
		/usr/local/qwt-5.2.2/include/qwt_plot.h \
		/usr/local/qwt-5.2.2/include/qwt_array.h \
		/usr/local/qwt-5.2.2/include/qwt_text.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_dict.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_item.h \
		/usr/local/qwt-5.2.2/include/qwt_legend_itemmanager.h \
		/usr/local/qwt-5.2.2/include/qwt_double_rect.h \
		/usr/local/qwt-5.2.2/include/qwt_scale_map.h \
		/usr/local/qwt-5.2.2/include/qwt_math.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_printfilter.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_zoomer.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_picker.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_canvas.h \
		/usr/local/qwt-5.2.2/include/qwt_picker.h \
		/usr/local/qwt-5.2.2/include/qwt_polygon.h \
		/usr/local/qwt-5.2.2/include/qwt_event_pattern.h \
		/usr/local/qwt-5.2.2/include/qwt_painter.h \
		/usr/local/qwt-5.2.2/include/qwt_layout_metrics.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_marker.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_curve.h \
		/usr/local/qwt-5.2.2/include/qwt_data.h \
		/usr/local/qwt-5.2.2/include/qwt_scale_widget.h \
		/usr/local/qwt-5.2.2/include/qwt_scale_draw.h \
		/usr/local/qwt-5.2.2/include/qwt_abstract_scale_draw.h \
		/usr/local/qwt-5.2.2/include/qwt_scale_div.h \
		/usr/local/qwt-5.2.2/include/qwt_valuelist.h \
		/usr/local/qwt-5.2.2/include/qwt_double_interval.h \
		/usr/local/qwt-5.2.2/include/qwt_legend.h \
		LogWidget.h \
		AppConfig.h \
		ConfigFile/ConfigFile.h \
		ui_PreferencesDialog.h \
		TwoThetaWindow.h \
		ui_MacroDialog.h \
		/usr/local/qwt-5.2.2/include/qwt_symbol.h \
		TwoThetaPlot.h \
		ui_MineralSearchDialog.h \
		FilmWidget.h
	/Users/japetrus/PhD/Programs/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ FilmWidget.h -o moc_FilmWidget.cpp

moc_AppWindow.cpp: FilmWidget.h \
		/usr/local/qwt-5.2.2/include/qwt.h \
		/usr/local/qwt-5.2.2/include/qwt_global.h \
		/usr/local/qwt-5.2.2/include/qwt_plot.h \
		/usr/local/qwt-5.2.2/include/qwt_array.h \
		/usr/local/qwt-5.2.2/include/qwt_text.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_dict.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_item.h \
		/usr/local/qwt-5.2.2/include/qwt_legend_itemmanager.h \
		/usr/local/qwt-5.2.2/include/qwt_double_rect.h \
		/usr/local/qwt-5.2.2/include/qwt_scale_map.h \
		/usr/local/qwt-5.2.2/include/qwt_math.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_printfilter.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_zoomer.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_picker.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_canvas.h \
		/usr/local/qwt-5.2.2/include/qwt_picker.h \
		/usr/local/qwt-5.2.2/include/qwt_polygon.h \
		/usr/local/qwt-5.2.2/include/qwt_event_pattern.h \
		/usr/local/qwt-5.2.2/include/qwt_painter.h \
		/usr/local/qwt-5.2.2/include/qwt_layout_metrics.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_marker.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_curve.h \
		/usr/local/qwt-5.2.2/include/qwt_data.h \
		/usr/local/qwt-5.2.2/include/qwt_scale_widget.h \
		/usr/local/qwt-5.2.2/include/qwt_scale_draw.h \
		/usr/local/qwt-5.2.2/include/qwt_abstract_scale_draw.h \
		/usr/local/qwt-5.2.2/include/qwt_scale_div.h \
		/usr/local/qwt-5.2.2/include/qwt_valuelist.h \
		/usr/local/qwt-5.2.2/include/qwt_double_interval.h \
		/usr/local/qwt-5.2.2/include/qwt_legend.h \
		LogWidget.h \
		AppConfig.h \
		ConfigFile/ConfigFile.h \
		ui_PreferencesDialog.h \
		TwoThetaWindow.h \
		ui_MacroDialog.h \
		/usr/local/qwt-5.2.2/include/qwt_symbol.h \
		TwoThetaPlot.h \
		ui_MineralSearchDialog.h \
		ui_GeometryDialog.h \
		ui_ImageDialog.h \
		AppWindow.h
	/Users/japetrus/PhD/Programs/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ AppWindow.h -o moc_AppWindow.cpp

moc_AppConfig.cpp: ConfigFile/ConfigFile.h \
		ui_PreferencesDialog.h \
		AppConfig.h
	/Users/japetrus/PhD/Programs/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ AppConfig.h -o moc_AppConfig.cpp

moc_LogWidget.cpp: LogWidget.h
	/Users/japetrus/PhD/Programs/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ LogWidget.h -o moc_LogWidget.cpp

moc_TwoThetaWindow.cpp: ui_MacroDialog.h \
		/usr/local/qwt-5.2.2/include/qwt.h \
		/usr/local/qwt-5.2.2/include/qwt_global.h \
		/usr/local/qwt-5.2.2/include/qwt_plot.h \
		/usr/local/qwt-5.2.2/include/qwt_array.h \
		/usr/local/qwt-5.2.2/include/qwt_text.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_dict.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_item.h \
		/usr/local/qwt-5.2.2/include/qwt_legend_itemmanager.h \
		/usr/local/qwt-5.2.2/include/qwt_double_rect.h \
		/usr/local/qwt-5.2.2/include/qwt_scale_map.h \
		/usr/local/qwt-5.2.2/include/qwt_math.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_printfilter.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_zoomer.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_picker.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_canvas.h \
		/usr/local/qwt-5.2.2/include/qwt_picker.h \
		/usr/local/qwt-5.2.2/include/qwt_polygon.h \
		/usr/local/qwt-5.2.2/include/qwt_event_pattern.h \
		/usr/local/qwt-5.2.2/include/qwt_painter.h \
		/usr/local/qwt-5.2.2/include/qwt_layout_metrics.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_marker.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_curve.h \
		/usr/local/qwt-5.2.2/include/qwt_data.h \
		/usr/local/qwt-5.2.2/include/qwt_scale_widget.h \
		/usr/local/qwt-5.2.2/include/qwt_scale_draw.h \
		/usr/local/qwt-5.2.2/include/qwt_abstract_scale_draw.h \
		/usr/local/qwt-5.2.2/include/qwt_scale_div.h \
		/usr/local/qwt-5.2.2/include/qwt_valuelist.h \
		/usr/local/qwt-5.2.2/include/qwt_double_interval.h \
		/usr/local/qwt-5.2.2/include/qwt_legend.h \
		/usr/local/qwt-5.2.2/include/qwt_symbol.h \
		AppConfig.h \
		ConfigFile/ConfigFile.h \
		ui_PreferencesDialog.h \
		TwoThetaPlot.h \
		ui_MineralSearchDialog.h \
		TwoThetaWindow.h
	/Users/japetrus/PhD/Programs/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ TwoThetaWindow.h -o moc_TwoThetaWindow.cpp

compiler_rcc_make_all: qrc_AppResources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_AppResources.cpp
qrc_AppResources.cpp: AppResources.qrc \
		Resources/open.png \
		Resources/print.png \
		Resources/prefs.png \
		Resources/opt.png \
		Resources/apply.png \
		Resources/geometry.png \
		Resources/log.png \
		Resources/viewmag.png \
		Resources/region.png \
		Resources/find.png \
		Resources/offset.png \
		Resources/filesave.png \
		Resources/savecsv.png \
		Resources/move.png \
		Resources/int.png \
		Resources/icon.icns \
		Resources/bgs.png \
		Resources/reset.png \
		Resources/mult.png \
		Resources/exclude.png \
		Resources/savetiff.png \
		Resources/resize.png \
		Resources/saveudf.png \
		Resources/truncate.png \
		Resources/minmax.png
	/Users/japetrus/PhD/Programs/QtSDK/Desktop/Qt/474/gcc/bin/rcc -name AppResources AppResources.qrc -o qrc_AppResources.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all: ui_PreferencesDialog.h ui_GeometryDialog.h ui_MineralSearchDialog.h ui_ImageDialog.h ui_MacroDialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_PreferencesDialog.h ui_GeometryDialog.h ui_MineralSearchDialog.h ui_ImageDialog.h ui_MacroDialog.h
ui_PreferencesDialog.h: PreferencesDialog.ui
	/Users/japetrus/PhD/Programs/QtSDK/Desktop/Qt/474/gcc/bin/uic PreferencesDialog.ui -o ui_PreferencesDialog.h

ui_GeometryDialog.h: GeometryDialog.ui
	/Users/japetrus/PhD/Programs/QtSDK/Desktop/Qt/474/gcc/bin/uic GeometryDialog.ui -o ui_GeometryDialog.h

ui_MineralSearchDialog.h: MineralSearchDialog.ui
	/Users/japetrus/PhD/Programs/QtSDK/Desktop/Qt/474/gcc/bin/uic MineralSearchDialog.ui -o ui_MineralSearchDialog.h

ui_ImageDialog.h: ImageDialog.ui
	/Users/japetrus/PhD/Programs/QtSDK/Desktop/Qt/474/gcc/bin/uic ImageDialog.ui -o ui_ImageDialog.h

ui_MacroDialog.h: MacroDialog.ui
	/Users/japetrus/PhD/Programs/QtSDK/Desktop/Qt/474/gcc/bin/uic MacroDialog.ui -o ui_MacroDialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp AppWindow.h \
		FilmWidget.h \
		/usr/local/qwt-5.2.2/include/qwt.h \
		/usr/local/qwt-5.2.2/include/qwt_global.h \
		/usr/local/qwt-5.2.2/include/qwt_plot.h \
		/usr/local/qwt-5.2.2/include/qwt_array.h \
		/usr/local/qwt-5.2.2/include/qwt_text.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_dict.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_item.h \
		/usr/local/qwt-5.2.2/include/qwt_legend_itemmanager.h \
		/usr/local/qwt-5.2.2/include/qwt_double_rect.h \
		/usr/local/qwt-5.2.2/include/qwt_scale_map.h \
		/usr/local/qwt-5.2.2/include/qwt_math.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_printfilter.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_zoomer.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_picker.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_canvas.h \
		/usr/local/qwt-5.2.2/include/qwt_picker.h \
		/usr/local/qwt-5.2.2/include/qwt_polygon.h \
		/usr/local/qwt-5.2.2/include/qwt_event_pattern.h \
		/usr/local/qwt-5.2.2/include/qwt_painter.h \
		/usr/local/qwt-5.2.2/include/qwt_layout_metrics.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_marker.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_curve.h \
		/usr/local/qwt-5.2.2/include/qwt_data.h \
		/usr/local/qwt-5.2.2/include/qwt_scale_widget.h \
		/usr/local/qwt-5.2.2/include/qwt_scale_draw.h \
		/usr/local/qwt-5.2.2/include/qwt_abstract_scale_draw.h \
		/usr/local/qwt-5.2.2/include/qwt_scale_div.h \
		/usr/local/qwt-5.2.2/include/qwt_valuelist.h \
		/usr/local/qwt-5.2.2/include/qwt_double_interval.h \
		/usr/local/qwt-5.2.2/include/qwt_legend.h \
		LogWidget.h \
		AppConfig.h \
		ConfigFile/ConfigFile.h \
		ui_PreferencesDialog.h \
		TwoThetaWindow.h \
		ui_MacroDialog.h \
		/usr/local/qwt-5.2.2/include/qwt_symbol.h \
		TwoThetaPlot.h \
		ui_MineralSearchDialog.h \
		ui_GeometryDialog.h \
		ui_ImageDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

ConfigFile.o: ConfigFile/ConfigFile.cpp ConfigFile/ConfigFile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ConfigFile.o ConfigFile/ConfigFile.cpp

TwoThetaPlot.o: TwoThetaPlot.cpp TwoThetaPlot.h \
		/usr/local/qwt-5.2.2/include/qwt.h \
		/usr/local/qwt-5.2.2/include/qwt_global.h \
		/usr/local/qwt-5.2.2/include/qwt_plot.h \
		/usr/local/qwt-5.2.2/include/qwt_array.h \
		/usr/local/qwt-5.2.2/include/qwt_text.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_dict.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_item.h \
		/usr/local/qwt-5.2.2/include/qwt_legend_itemmanager.h \
		/usr/local/qwt-5.2.2/include/qwt_double_rect.h \
		/usr/local/qwt-5.2.2/include/qwt_scale_map.h \
		/usr/local/qwt-5.2.2/include/qwt_math.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_printfilter.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_zoomer.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_picker.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_canvas.h \
		/usr/local/qwt-5.2.2/include/qwt_picker.h \
		/usr/local/qwt-5.2.2/include/qwt_polygon.h \
		/usr/local/qwt-5.2.2/include/qwt_event_pattern.h \
		/usr/local/qwt-5.2.2/include/qwt_painter.h \
		/usr/local/qwt-5.2.2/include/qwt_layout_metrics.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_marker.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_curve.h \
		/usr/local/qwt-5.2.2/include/qwt_data.h \
		/usr/local/qwt-5.2.2/include/qwt_scale_widget.h \
		/usr/local/qwt-5.2.2/include/qwt_scale_draw.h \
		/usr/local/qwt-5.2.2/include/qwt_abstract_scale_draw.h \
		/usr/local/qwt-5.2.2/include/qwt_scale_div.h \
		/usr/local/qwt-5.2.2/include/qwt_valuelist.h \
		/usr/local/qwt-5.2.2/include/qwt_double_interval.h \
		/usr/local/qwt-5.2.2/include/qwt_legend.h \
		/usr/local/qwt-5.2.2/include/qwt_symbol.h \
		AppConfig.h \
		ConfigFile/ConfigFile.h \
		ui_PreferencesDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TwoThetaPlot.o TwoThetaPlot.cpp

AppWindow.o: AppWindow.cpp AppWindow.h \
		FilmWidget.h \
		/usr/local/qwt-5.2.2/include/qwt.h \
		/usr/local/qwt-5.2.2/include/qwt_global.h \
		/usr/local/qwt-5.2.2/include/qwt_plot.h \
		/usr/local/qwt-5.2.2/include/qwt_array.h \
		/usr/local/qwt-5.2.2/include/qwt_text.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_dict.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_item.h \
		/usr/local/qwt-5.2.2/include/qwt_legend_itemmanager.h \
		/usr/local/qwt-5.2.2/include/qwt_double_rect.h \
		/usr/local/qwt-5.2.2/include/qwt_scale_map.h \
		/usr/local/qwt-5.2.2/include/qwt_math.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_printfilter.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_zoomer.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_picker.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_canvas.h \
		/usr/local/qwt-5.2.2/include/qwt_picker.h \
		/usr/local/qwt-5.2.2/include/qwt_polygon.h \
		/usr/local/qwt-5.2.2/include/qwt_event_pattern.h \
		/usr/local/qwt-5.2.2/include/qwt_painter.h \
		/usr/local/qwt-5.2.2/include/qwt_layout_metrics.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_marker.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_curve.h \
		/usr/local/qwt-5.2.2/include/qwt_data.h \
		/usr/local/qwt-5.2.2/include/qwt_scale_widget.h \
		/usr/local/qwt-5.2.2/include/qwt_scale_draw.h \
		/usr/local/qwt-5.2.2/include/qwt_abstract_scale_draw.h \
		/usr/local/qwt-5.2.2/include/qwt_scale_div.h \
		/usr/local/qwt-5.2.2/include/qwt_valuelist.h \
		/usr/local/qwt-5.2.2/include/qwt_double_interval.h \
		/usr/local/qwt-5.2.2/include/qwt_legend.h \
		LogWidget.h \
		AppConfig.h \
		ConfigFile/ConfigFile.h \
		ui_PreferencesDialog.h \
		TwoThetaWindow.h \
		ui_MacroDialog.h \
		/usr/local/qwt-5.2.2/include/qwt_symbol.h \
		TwoThetaPlot.h \
		ui_MineralSearchDialog.h \
		ui_GeometryDialog.h \
		ui_ImageDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AppWindow.o AppWindow.cpp

FilmWidget.o: FilmWidget.cpp FilmWidget.h \
		/usr/local/qwt-5.2.2/include/qwt.h \
		/usr/local/qwt-5.2.2/include/qwt_global.h \
		/usr/local/qwt-5.2.2/include/qwt_plot.h \
		/usr/local/qwt-5.2.2/include/qwt_array.h \
		/usr/local/qwt-5.2.2/include/qwt_text.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_dict.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_item.h \
		/usr/local/qwt-5.2.2/include/qwt_legend_itemmanager.h \
		/usr/local/qwt-5.2.2/include/qwt_double_rect.h \
		/usr/local/qwt-5.2.2/include/qwt_scale_map.h \
		/usr/local/qwt-5.2.2/include/qwt_math.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_printfilter.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_zoomer.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_picker.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_canvas.h \
		/usr/local/qwt-5.2.2/include/qwt_picker.h \
		/usr/local/qwt-5.2.2/include/qwt_polygon.h \
		/usr/local/qwt-5.2.2/include/qwt_event_pattern.h \
		/usr/local/qwt-5.2.2/include/qwt_painter.h \
		/usr/local/qwt-5.2.2/include/qwt_layout_metrics.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_marker.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_curve.h \
		/usr/local/qwt-5.2.2/include/qwt_data.h \
		/usr/local/qwt-5.2.2/include/qwt_scale_widget.h \
		/usr/local/qwt-5.2.2/include/qwt_scale_draw.h \
		/usr/local/qwt-5.2.2/include/qwt_abstract_scale_draw.h \
		/usr/local/qwt-5.2.2/include/qwt_scale_div.h \
		/usr/local/qwt-5.2.2/include/qwt_valuelist.h \
		/usr/local/qwt-5.2.2/include/qwt_double_interval.h \
		/usr/local/qwt-5.2.2/include/qwt_legend.h \
		LogWidget.h \
		AppConfig.h \
		ConfigFile/ConfigFile.h \
		ui_PreferencesDialog.h \
		TwoThetaWindow.h \
		ui_MacroDialog.h \
		/usr/local/qwt-5.2.2/include/qwt_symbol.h \
		TwoThetaPlot.h \
		ui_MineralSearchDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FilmWidget.o FilmWidget.cpp

AppConfig.o: AppConfig.cpp AppConfig.h \
		ConfigFile/ConfigFile.h \
		ui_PreferencesDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AppConfig.o AppConfig.cpp

TwoThetaWindow.o: TwoThetaWindow.cpp TwoThetaWindow.h \
		ui_MacroDialog.h \
		/usr/local/qwt-5.2.2/include/qwt.h \
		/usr/local/qwt-5.2.2/include/qwt_global.h \
		/usr/local/qwt-5.2.2/include/qwt_plot.h \
		/usr/local/qwt-5.2.2/include/qwt_array.h \
		/usr/local/qwt-5.2.2/include/qwt_text.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_dict.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_item.h \
		/usr/local/qwt-5.2.2/include/qwt_legend_itemmanager.h \
		/usr/local/qwt-5.2.2/include/qwt_double_rect.h \
		/usr/local/qwt-5.2.2/include/qwt_scale_map.h \
		/usr/local/qwt-5.2.2/include/qwt_math.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_printfilter.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_zoomer.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_picker.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_canvas.h \
		/usr/local/qwt-5.2.2/include/qwt_picker.h \
		/usr/local/qwt-5.2.2/include/qwt_polygon.h \
		/usr/local/qwt-5.2.2/include/qwt_event_pattern.h \
		/usr/local/qwt-5.2.2/include/qwt_painter.h \
		/usr/local/qwt-5.2.2/include/qwt_layout_metrics.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_marker.h \
		/usr/local/qwt-5.2.2/include/qwt_plot_curve.h \
		/usr/local/qwt-5.2.2/include/qwt_data.h \
		/usr/local/qwt-5.2.2/include/qwt_scale_widget.h \
		/usr/local/qwt-5.2.2/include/qwt_scale_draw.h \
		/usr/local/qwt-5.2.2/include/qwt_abstract_scale_draw.h \
		/usr/local/qwt-5.2.2/include/qwt_scale_div.h \
		/usr/local/qwt-5.2.2/include/qwt_valuelist.h \
		/usr/local/qwt-5.2.2/include/qwt_double_interval.h \
		/usr/local/qwt-5.2.2/include/qwt_legend.h \
		/usr/local/qwt-5.2.2/include/qwt_symbol.h \
		AppConfig.h \
		ConfigFile/ConfigFile.h \
		ui_PreferencesDialog.h \
		TwoThetaPlot.h \
		ui_MineralSearchDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TwoThetaWindow.o TwoThetaWindow.cpp

moc_TwoThetaPlot.o: moc_TwoThetaPlot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TwoThetaPlot.o moc_TwoThetaPlot.cpp

moc_FilmWidget.o: moc_FilmWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FilmWidget.o moc_FilmWidget.cpp

moc_AppWindow.o: moc_AppWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_AppWindow.o moc_AppWindow.cpp

moc_AppConfig.o: moc_AppConfig.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_AppConfig.o moc_AppConfig.cpp

moc_LogWidget.o: moc_LogWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_LogWidget.o moc_LogWidget.cpp

moc_TwoThetaWindow.o: moc_TwoThetaWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TwoThetaWindow.o moc_TwoThetaWindow.cpp

qrc_AppResources.o: qrc_AppResources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_AppResources.o qrc_AppResources.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/Users/japetrus/PhD/ProgramsGIT/DIIS/src/../bin/ || $(MKDIR) $(INSTALL_ROOT)/Users/japetrus/PhD/ProgramsGIT/DIIS/src/../bin/ 
	$(DEL_FILE) -r "$(INSTALL_ROOT)/Users/japetrus/PhD/ProgramsGIT/DIIS/bin/DIIS.app"
	
	-$(INSTALL_DIR) "../bin/DIIS.app" "$(INSTALL_ROOT)/Users/japetrus/PhD/ProgramsGIT/DIIS/bin/DIIS.app"

uninstall_target:  FORCE
	-$(DEL_FILE) -r "$(INSTALL_ROOT)/Users/japetrus/PhD/ProgramsGIT/DIIS/bin/DIIS.app"
	-$(DEL_DIR) $(INSTALL_ROOT)/Users/japetrus/PhD/ProgramsGIT/DIIS/src/../bin/ 


install_sources: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/Users/japetrus/PhD/ProgramsGIT/DIIS/src/./ || $(MKDIR) $(INSTALL_ROOT)/Users/japetrus/PhD/ProgramsGIT/DIIS/src/./ 
	-$(INSTALL_FILE) /Users/japetrus/PhD/ProgramsGIT/DIIS/src/main.cpp $(INSTALL_ROOT)/Users/japetrus/PhD/ProgramsGIT/DIIS/src/./
	-$(INSTALL_FILE) /Users/japetrus/PhD/ProgramsGIT/DIIS/src/ConfigFile/ConfigFile.cpp $(INSTALL_ROOT)/Users/japetrus/PhD/ProgramsGIT/DIIS/src/./
	-$(INSTALL_FILE) /Users/japetrus/PhD/ProgramsGIT/DIIS/src/TwoThetaPlot.cpp $(INSTALL_ROOT)/Users/japetrus/PhD/ProgramsGIT/DIIS/src/./
	-$(INSTALL_FILE) /Users/japetrus/PhD/ProgramsGIT/DIIS/src/AppWindow.cpp $(INSTALL_ROOT)/Users/japetrus/PhD/ProgramsGIT/DIIS/src/./
	-$(INSTALL_FILE) /Users/japetrus/PhD/ProgramsGIT/DIIS/src/FilmWidget.cpp $(INSTALL_ROOT)/Users/japetrus/PhD/ProgramsGIT/DIIS/src/./
	-$(INSTALL_FILE) /Users/japetrus/PhD/ProgramsGIT/DIIS/src/AppConfig.cpp $(INSTALL_ROOT)/Users/japetrus/PhD/ProgramsGIT/DIIS/src/./
	-$(INSTALL_FILE) /Users/japetrus/PhD/ProgramsGIT/DIIS/src/TwoThetaWindow.cpp $(INSTALL_ROOT)/Users/japetrus/PhD/ProgramsGIT/DIIS/src/./
	-$(INSTALL_FILE) /Users/japetrus/PhD/ProgramsGIT/DIIS/src/ConfigFile/ConfigFile.h $(INSTALL_ROOT)/Users/japetrus/PhD/ProgramsGIT/DIIS/src/./
	-$(INSTALL_FILE) /Users/japetrus/PhD/ProgramsGIT/DIIS/src/TwoThetaPlot.h $(INSTALL_ROOT)/Users/japetrus/PhD/ProgramsGIT/DIIS/src/./
	-$(INSTALL_FILE) /Users/japetrus/PhD/ProgramsGIT/DIIS/src/FilmWidget.h $(INSTALL_ROOT)/Users/japetrus/PhD/ProgramsGIT/DIIS/src/./
	-$(INSTALL_FILE) /Users/japetrus/PhD/ProgramsGIT/DIIS/src/AppWindow.h $(INSTALL_ROOT)/Users/japetrus/PhD/ProgramsGIT/DIIS/src/./
	-$(INSTALL_FILE) /Users/japetrus/PhD/ProgramsGIT/DIIS/src/AppConfig.h $(INSTALL_ROOT)/Users/japetrus/PhD/ProgramsGIT/DIIS/src/./
	-$(INSTALL_FILE) /Users/japetrus/PhD/ProgramsGIT/DIIS/src/LogWidget.h $(INSTALL_ROOT)/Users/japetrus/PhD/ProgramsGIT/DIIS/src/./
	-$(INSTALL_FILE) /Users/japetrus/PhD/ProgramsGIT/DIIS/src/TwoThetaWindow.h $(INSTALL_ROOT)/Users/japetrus/PhD/ProgramsGIT/DIIS/src/./
	-$(INSTALL_FILE) /Users/japetrus/PhD/ProgramsGIT/DIIS/src/DIIS.pro $(INSTALL_ROOT)/Users/japetrus/PhD/ProgramsGIT/DIIS/src/./


uninstall_sources:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/Users/japetrus/PhD/ProgramsGIT/DIIS/src/./main.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/Users/japetrus/PhD/ProgramsGIT/DIIS/src/./ConfigFile.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/Users/japetrus/PhD/ProgramsGIT/DIIS/src/./TwoThetaPlot.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/Users/japetrus/PhD/ProgramsGIT/DIIS/src/./AppWindow.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/Users/japetrus/PhD/ProgramsGIT/DIIS/src/./FilmWidget.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/Users/japetrus/PhD/ProgramsGIT/DIIS/src/./AppConfig.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/Users/japetrus/PhD/ProgramsGIT/DIIS/src/./TwoThetaWindow.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/Users/japetrus/PhD/ProgramsGIT/DIIS/src/./ConfigFile.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/Users/japetrus/PhD/ProgramsGIT/DIIS/src/./TwoThetaPlot.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/Users/japetrus/PhD/ProgramsGIT/DIIS/src/./FilmWidget.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/Users/japetrus/PhD/ProgramsGIT/DIIS/src/./AppWindow.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/Users/japetrus/PhD/ProgramsGIT/DIIS/src/./AppConfig.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/Users/japetrus/PhD/ProgramsGIT/DIIS/src/./LogWidget.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/Users/japetrus/PhD/ProgramsGIT/DIIS/src/./TwoThetaWindow.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/Users/japetrus/PhD/ProgramsGIT/DIIS/src/./DIIS.pro
	-$(DEL_DIR) $(INSTALL_ROOT)/Users/japetrus/PhD/ProgramsGIT/DIIS/src/./ 


install:  install_target install_sources  FORCE

uninstall: uninstall_target uninstall_sources   FORCE

FORCE:

